---
# tasks file for mysql_db
            - name: 'Install-mysql'
              dnf: name={{ item }} state=present
              with_items:
                    - mysql-server
                      #                    - mysql-client
            - name: 'Start services' 
              service:
                      name: mysqld
                      enabled: yes
                      state: started      
            - name: 'Create APP DB'
              mysql_db: name={{ db_name }} state=present
            - name: 'DB Users'
              mysql_user:
                      name: "{{ db_user }}"
                      password: "{{ db_user_password }}"   
                      priv: '*.*:ALL'
                      state: present 
                      host: '%'

